### ISSUE TITLE
Stream authentication question

### ISSUE THREAD

**Issue by lleoll1** [WrathChaos/MJPEGStreamLib#3]
I know that this is an old project but I have already tried to analyse the library but I can't get stream authentication working. Does anyone know the syntax I need to use to pass a username and password. Thanks in advance !

**Comment by WrathChaos** [comment]
Hello @lleoll1,
Wow, 2 years passed I made this library :) Fortunately, I'm still maintain the project. I've never tried to work with authentication MJPEGStream. I did not have a chance. Can you provide me a test so I can help you :)

**Comment by WrathChaos** [comment]
@lleoll1 This library is heavily based on another non working one. But still it's README could be useful. Can you try this: 
https://github.com/freedom27/MjpegStreamingKit#authentication

If it works, I will update the README ASAP

**Comment by WrathChaos** [comment]
I closed it for now, if you still have the same problem please re-write it and I will re-open the issue :)

**Comment by lleoll1** [comment]
I have tried to use`NSURL(string:"http://username:password@mjpeg.streaming.url/movie.mjpeg")` which was mentioned in the readme that you sent, however when I use it in the Viewcontroller instead of the line `let url = **URL(string: "http://---------")**` I get lots of errors about using NSURL instead of URL. Sorry for the very slow reply.

**Comment by WrathChaos** [comment]
@lleoll1,
NSURL and URL are basically the same things. URL is just a renamed from Apple. Can you share me with source code with the errors?

**Comment by lleoll1** [comment]
I am just working in the example project that came with the library, but [here](https://drive.google.com/drive/folders/18L4vWgHisNSbQaqwG3pnSOvHAy1DYj0b?usp=sharing) it is with some changes anyway.

**Comment by WrathChaos** [comment]
@lleoll1 I'm going to try this example when I'm available :)

**Comment by WrathChaos** [comment]
@lleoll1 I could not download the project, I have no idea why. Can you create a simple repo for me?
