### ISSUE TITLE
NSMutableData -> Data

### ISSUE THREAD

**Issue by dim971** [WrathChaos/MJPEGStreamLib#4]
https://github.com/WrathChaos/MJPEGStreamLib/blob/285d2b981d729032e13a98a0d7a86f28c6586dd1/MJPEGStreamLib/Classes/MJPEGStreamLib.swift#L19

Why using `NSMutableData`? you could simply use `Data` 🙂

**Comment by WrathChaos** [comment]
When I wrote this library, I simply use NSMutableData after the migration it just changed the name to much simpler one, the Data :) I can change it for the next release.
