### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by Goule** [WrathChaos/MJPEGStreamLib#7]
Hello ! 

Do you know if it's possible to get sound from MJPEG stream ? 

Thanks for this library, I was trying this with socket but it's really much simpler like you did :-) 

Thanks

**Comment by WrathChaos** [comment]
Hello @Goule,
Actually, I think it is not but I need to research about it :)

**Comment by WrathChaos** [comment]
Hello again @Goule,

I researched about the MPJEG Stream with audio feature and the proper way of doing it is to use `ffmpeg`, `libav` and an `RTMP server`. Unfortunately, I do not have a deep knowledge of that.
